export const FETCH_MENUS_DATA_REQUEST = 'FETCH_MENUS_DATA_REQUEST';
export const FETCH_MENUS_DATA_SUCCESS = 'FETCH_MENUS_DATA_SUCCESS';
export const FETCH_MENUS_DATA_FAIL = 'FETCH_MENUS_DATA_FAIL';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const ADD_ITEMS_TO_CART = 'ADD_ITEMS_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const FILTER_MENU_TYPES = 'FILTER_MENU_TYPES';